package com.mvc.suspendProjects;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.mvc.suspendProjects.*;

/* 
 * Generated by Natileo - Velociraptor
 * on Fri Nov 05 01:18:18 CET 2010
 * hemca.com
 * by Strzelewicz Alexandre
 */

@Controller
@RequestMapping(value="/suspendProjects")
public class SuspendProjectsController {
	@Autowired
	private SuspendProjectsService suspendProjectsService;
	
	@RequestMapping(value="/read.action")
	public @ResponseBody Map<String,? extends Object> getSuspendProjects() throws Exception {
		try {
			List<SuspendProjects> suspendProjects = suspendProjectsService.getSuspendProjectsList();
			return getMap(suspendProjects);
		}catch (Exception e){
			return getModelMapError("Failure");
		}
	}
	
	@RequestMapping(value="/read.action", params={"start", "limit"})
	public @ResponseBody Map<String,? extends Object> getSuspendProjects(@RequestParam int start,
																	 @RequestParam int limit) 
																	 throws Exception {
		try {
			List<SuspendProjects> suspendProjects = suspendProjectsService.getSuspendProjectsList(start, limit);
			return getMap(suspendProjects);
		}catch (Exception e){
			return getModelMapError("Failure");
		}
	}
	
	@RequestMapping(value="/read.action", params={"start", 
												  "limit", 
												  "filter[0][data][type]",
												  "filter[0][data][value]", 
												  "filter[0][field]"})
	public @ResponseBody Map<String,? extends Object> getProj(@RequestParam int start,
															  @RequestParam int limit,
															  @RequestParam("filter[0][data][type]") String type,
															  @RequestParam("filter[0][data][value]") String value,
															  @RequestParam("filter[0][field]") String field) 
															  throws Exception {
		try {
			List<SuspendProjects> suspendProjects = suspendProjectsService.getSuspendProjectsList(start, limit, type, value, field);
			return getMap(suspendProjects);
		}catch (Exception e){
			return getModelMapError("Failure");
		}
	}
	@RequestMapping(value="/create.action")
	public @ResponseBody Map<String,? extends Object> createSuspendProjects(@RequestParam Object data) throws Exception{
		try{
			SuspendProjects suspendProjects = suspendProjectsService.createNewSuspendProjects(data);
			return getMapSolo(suspendProjects);
		} catch (Exception e) {
			return getModelMapError("Error trying to update SuspendProjects.");
		}
	}
	
	@RequestMapping(value="/update.action")
	public @ResponseBody Map<String,? extends Object> updateSuspendProjects(@RequestParam Object data) throws Exception{
		try{
			suspendProjectsService.createNewSuspendProjects(data);
			Map<String,Object> modelMap = new HashMap<String,Object>(3);
			modelMap.put("success", true);
			return modelMap;
		} catch (Exception e) {
			return getModelMapError("Error trying to update SuspendProjects.");
		}
	}
	
	@RequestMapping(value="/delete.action")
	public @ResponseBody Map<String,? extends Object> delete(@RequestParam Object data) throws Exception {
		try{
			suspendProjectsService.deleteSuspendProjects(data);
			Map<String,Object> modelMap = new HashMap<String,Object>(3);
			modelMap.put("success", true);
			return modelMap;
		} catch (Exception e) {
			return getModelMapError("Error trying to delete SuspendProjects.");
		}
	}
	
	private Map<String,Object> getMapSolo(SuspendProjects object){
		Map<String,Object> modelMap = new HashMap<String,Object>(4);
		modelMap.put("data", object);
		modelMap.put("success", true);
		return modelMap;
	}
	
	private Map<String,Object> getMap(List<SuspendProjects> object){
		Map<String,Object> modelMap = new HashMap<String,Object>(4);
		modelMap.put("total", object.size());
		modelMap.put("data", object);
		modelMap.put("success", true);
		return modelMap;
	}
	
	private Map<String,Object> getModelMapError(String msg){
		Map<String,Object> modelMap = new HashMap<String,Object>(2);
		modelMap.put("message", msg);
		modelMap.put("success", false);
		return modelMap;
	} 

}
