package com.mvc.inprogressProjects;

import org.codehaus.jackson.annotate.JsonAutoDetect;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/*
 * Generated by Natileo - Velociraptor
 * on Thu Nov 04 21:12:37 CET 2010
 * hemca.com
 * Strzelewicz Alexandre
 */

@JsonAutoDetect
@Entity
@Table(name = "inprogress_projects", schema = "public")
public class InprogressProjects {
  private String projName;
  private String progress;
  private String field1;
  private String field2;
  private String beginDate;
  private String endDate;
  private String previsionDate;
  private String projCmt;
  private String priority;
  private String previsionTime;
  private String spentTime;
  private String projLogo;
  private String projLink;
  private int id;
 
  public InprogressProjects(){
  }
 
  @Column(name = "proj_name", length = 200)
  public String getProjName() {
    return this.projName;
  }
  
  public void setProjName(String projName) {
    this.projName = projName;
  } 

  @Column(name = "progress", length = 20)
  public String getProgress() {
    return this.progress;
  }
  
  public void setProgress(String progress) {
    this.progress = progress;
  } 

  @Column(name = "field_1", length = 200)
  public String getField1() {
    return this.field1;
  }
  
  public void setField1(String field1) {
    this.field1 = field1;
  } 

  @Column(name = "field_2", length = 200)
  public String getField2() {
    return this.field2;
  }
  
  public void setField2(String field2) {
    this.field2 = field2;
  } 

  @Column(name = "begin_date", length = 200)
  public String getBeginDate() {
    return this.beginDate;
  }
  
  public void setBeginDate(String beginDate) {
    this.beginDate = beginDate;
  } 

  @Column(name = "end_date", length = 200)
  public String getEndDate() {
    return this.endDate;
  }
  
  public void setEndDate(String endDate) {
    this.endDate = endDate;
  } 

  @Column(name = "prevision_date", length = 200)
  public String getPrevisionDate() {
    return this.previsionDate;
  }
  
  public void setPrevisionDate(String previsionDate) {
    this.previsionDate = previsionDate;
  } 

  @Column(name = "proj_cmt", length = 4000)
  public String getProjCmt() {
    return this.projCmt;
  }
  
  public void setProjCmt(String projCmt) {
    this.projCmt = projCmt;
  } 

  @Column(name = "priority", length = 200)
  public String getPriority() {
    return this.priority;
  }
  
  public void setPriority(String priority) {
    this.priority = priority;
  } 

  @Column(name = "prevision_time", length = 50)
  public String getPrevisionTime() {
    return this.previsionTime;
  }
  
  public void setPrevisionTime(String previsionTime) {
    this.previsionTime = previsionTime;
  } 

  @Column(name = "spent_time", length = 50)
  public String getSpentTime() {
    return this.spentTime;
  }
  
  public void setSpentTime(String spentTime) {
    this.spentTime = spentTime;
  } 

  @Column(name = "proj_logo", length = 200)
  public String getProjLogo() {
    return this.projLogo;
  }
  
  public void setProjLogo(String projLogo) {
    this.projLogo = projLogo;
  } 

  @Column(name = "proj_link", length = 200)
  public String getProjLink() {
    return this.projLink;
  }
  
  public void setProjLink(String projLink) {
    this.projLink = projLink;
  } 

  @Id
  @GeneratedValue
  @Column(name = "id", unique = true, nullable = false)
  public int getId() {
	return this.id;
  }
  
  public void setId(int id) {
    this.id = id;
  } 

}
